CREATE TABLE TICKET(
    TICKET_ID VARCHAR(255) NOT NULL,
    TICKET_CATEGORY VARCHAR(255),
    TICKET_CLIENT VARCHAR(255),
    TICKET_EMPLOYEE VARCHAR(255),
    TICKET_DATE VARCHAR(10),
    TICKET_DESCRIPTION VARCHAR(255),
    TICKET_STATUS VARCHAR(255),
    TICKET_PRIORITY VARCHAR(255));

CREATE TABLE CATEGORY(
    CATEGORY_ID VARCHAR(255) NOT NULL,
    CATEGORY_DESCRIPTION VARCHAR(255));

CREATE TABLE CLIENT(
    CLIENT_ID VARCHAR(255) NOT NULL,
    CLIENT_CPF VARCHAR(18),
    CLIENT_LOGIN VARCHAR(20),
    CLIENT_PASSWORD VARCHAR(20),
    CLIENT_NAME VARCHAR(255),
    CLIENT_EMAIL VARCHAR(255),
    CLIENT_DATE VARCHAR(10),
    CLIENT_CONTACT VARCHAR(16),
    CLIENT_LOG VARCHAR(255),
    CLIENT_NEIGH VARCHAR(255),
    CLIENT_NUMBER VARCHAR(255),
    CLIENT_ZIP VARCHAR(9),
    CLIENT_CITY VARCHAR(255),
    CLIENT_STATE VARCHAR(2));

CREATE TABLE EMPLOYEE(
    EMPLOYEE_ID VARCHAR(255) NOT NULL,
    EMPLOYEE_CPF VARCHAR(18),
    EMPLOYEE_LOGIN VARCHAR(20),
    EMPLOYEE_PASSWORD VARCHAR(20),
    EMPLOYEE_NAME VARCHAR(255),
    EMPLOYEE_EMAIL VARCHAR(255),
    EMPLOYEE_DATE VARCHAR(10),
    EMPLOYEE_CONTACT VARCHAR(16),
    EMPLOYEE_LOG VARCHAR(255),
    EMPLOYEE_NEIGH VARCHAR(255),
    EMPLOYEE_NUMBER VARCHAR(255),
    EMPLOYEE_ZIP VARCHAR(9),
    EMPLOYEE_CITY VARCHAR(255),
    EMPLOYEE_STATE VARCHAR(2));

CREATE TABLE PIECE(
    PIECE_ID VARCHAR(255) NOT NULL,
    PIECE_SERIAL VARCHAR(18),
    PIECE_TYPE VARCHAR(20),
    PIECE_CLIENT VARCHAR(255),
    PIECE_DESCRIPTION VARCHAR(255),
    PIECE_STATUS VARCHAR(255));

CREATE TABLE STOCK(
    STOCK_ID VARCHAR(255) NOT NULL,
    STOCK_DESCRIPTION VARCHAR(255),
    STOCK_QUANTITY INTEGER,
    STOCK_VALUE VARCHAR(20));

CREATE TABLE STOCKLOG(
    STOCKLOG_ID VARCHAR(255) NOT NULL,
    STOCKLOG_DESCRIPTION VARCHAR(255),
    STOCKLOG_QUANTITY VARCHAR(20),
    STOCKLOG_DATE VARCHAR(10),
    STOCKLOG_CLIENT VARCHAR(255),
    STOCKLOG_STATUS VARCHAR(20));

